# 友链页地址
# 参数说明：
# link：必填，在这里填写你的友链页面地址
LINK: [
     { link: "https://www.xiaoten.com/pages/links/" },  # 友链页地址1，修改为你的友链页地址
]

# 配置项友链
# enable：是否启用配置项友链 true/false
# json_api_or_path：支持通过提供 json 格式的友链配置，可以是本地文件路径，或者是一个 url 地址
# list字段填写格式：["name", "link", "avatar","suffix"]，其中：
#       name：必填，友链的名字
#       link：必填，友链主页地址
#       avatar：必填，头像地址
#       suffix：选填，自定义订阅后缀
SETTINGS_FRIENDS_LINKS: {
    enable: true,
    json_api_or_path: "",
    list: [
        ["小十博客", "https://www.xiaoten.com/", "https://www.xiaoten.com/avatar.png"],
        ["从良未遂", "https://www.jeffer.xyz/", "https://www.jeffer.xyz/wp-content/uploads/2023/01/cropped-2023010402181112.jpg"],
        ["Evan", "https://www.evan.xin/", "https://www.evan.xin/logo.png"],
        ["友人C", "https://www.ihewro.com", "https://www.ihewro.com/usr/uploads/time/67bad1fb8fe22.jpg"],
        ["枋柚梓", "https://inkss.cn/", "https://static.inkss.cn/img/avatar.avif"],
        ["SUUS", "https://suus.me/", "https://suus.me/icons/favicon.svg", "atom.xml"],
        ["空白Koobai", "https://koobai.com/", "https://img.koobai.com/koobai.webp"],
        ["MouT.me", "https://ghost.mout.me/", "https://ghost.mout.me/favicon.ico", "rss"], 
        ["游钓四方", "https://blog.lhasa.icu/", "https://blog.lhasa.icu/favicon.svg"],
        ["雨帆", "https://yufan.me/", "https://weavatar.com/avatar/fc0c337151f20f2bdb9e063a7f61ebb5d954424040daf081086f6fc2b8564353"],
        ["子夜松声", "https://xyzbz.cn/", "https://bu.dusays.com/2023/07/25/64bf920527086.png"],
        ["灰常记忆", "https://bestcherish.com/", "https://bestcherish.com/image/favicon.svg", "feed"],
        ["安静角落", "https://wuziya.com/", "https://weavatar.com/avatar/44a830f1733f4acca071dac524c256a7972853f976dfc57a8f9e706351fdfff7"],
        ["Jack's Space", "https://veryjack.com/", "https://veryjack.com/wp-content/uploads/2025/05/avatar_transparant-150x150.webp", "feed"],
        ["故事的程序猿", "https://blog.lichenghao.cn/", "https://blog.lichenghao.cn/avatar.svg", "article/rss.xml"],
        ["小白大学渣", "https://www.baihub.cn/", "https://www.baihub.cn/wp-content/uploads/2024/12/logo-middle.jpg"],
        ["旺东自留地", "https://wang618.cn/", "https://wang618.cn/img/%E6%88%91%E7%9A%84%E5%A4%B4%E5%83%8F/%E6%88%91%E7%9A%84%E5%A4%B4%E5%83%8F01.webp", "rss.php"],
    ]
}

# block site list
# 添加屏蔽站点，支持正则表达式
BLOCK_SITE: [
     "https://q.chyfh.com/",
     "https://bokehub.com/",
     "https://jiaohuiming.cn",
     "https://mout.me",
]

# 从每个主页中最多获取几篇文章，请设置一个正整数
# 设置为0表示无限制
MAX_POSTS_NUM:  5

# 过期文章清除（天）
OUTDATE_CLEAN: 180
